web:
  build: .
  volumes:
    - .:/app
  volumes_from:
    - bundle
  command: rails s -b '0.0.0.0'
  ports:
    - "3000:3000"
  environment:
    RACK_ENV: development
    RAILS_ENV: development
    DOCKER_HOST_IP: '10.0.2.2'
  links:
    - db
    - redis
    - sidekiq
bundle:
  image: busybox
  volumes:
    - /bundle
db:
  image: postgres:9.4
  environment:
    POSTGRES_PASSWORD: "78GO6i4o"
    POSTGRES_USER: "app"
  ports:
    - "5432:5432"
redis:
  image: redis
  volumes:
    - /data/redis
  ports:
    - "6379:6379"
sidekiq:
  build: .
  volumes:
    - .:/app
  volumes_from:
    - bundle
  command: sidekiq
  links:
    - db
    - redis
