web:
  build: .
  volumes:
    - .:/app
  command: rails s -b '0.0.0.0'
  ports:
    - "3000:3000"
  environment:
    RACK_ENV: development
    RAILS_ENV: development
    DOCKER_HOST_IP: '10.0.2.2'
  links:
    - db
db:
  image: postgres:9.4
  environment:
    POSTGRES_PASSWORD: "password"
    POSTGRES_USER: "user"
  ports:
    - "5432:5432"
